"use client";

import { useState } from "react";

interface Step4PreviewProps {
  proposal: string;
  clientName: string;
  projectName: string;
  onReset: () => void;
  onBack: () => void;
}

function renderMarkdown(md: string) {
  return md
    .replace(/^### (.*$)/gm, '<h3 class="text-lg font-bold text-navy mt-6 mb-2">$1</h3>')
    .replace(/^## (.*$)/gm, '<h2 class="text-xl font-bold text-navy mt-8 mb-3 border-b-2 border-gold/30 pb-2">$1</h2>')
    .replace(/^# (.*$)/gm, '<h1 class="text-2xl font-bold text-navy mt-8 mb-4">$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong class="font-bold text-navy">$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*$)/gm, '<li class="ml-4 mb-1">• $1</li>')
    .replace(/^\d+\. (.*$)/gm, '<li class="ml-4 mb-1">$1</li>')
    .replace(/\n\n/g, '</p><p class="mb-3">')
    .replace(/\n/g, "<br/>");
}

export default function Step4Preview({ proposal, clientName, projectName, onReset, onBack }: Step4PreviewProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(proposal);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-display font-bold text-ivory">Your Proposal</h2>
          <p className="text-sm text-slate">{projectName} for {clientName}</p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={handleCopy}
            className="px-4 py-2 text-sm bg-navy-mid text-gold border border-gold/30 rounded-lg hover:bg-navy-light transition-colors"
          >
            {copied ? "✓ Copied!" : "📋 Copy"}
          </button>
        </div>
      </div>

      {/* Proposal paper */}
      <div className="proposal-paper rounded-lg p-8 sm:p-12 max-h-[60vh] overflow-y-auto">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-display font-bold text-navy mb-1">{projectName}</h1>
          <p className="text-sm text-navy/60">Prepared for {clientName}</p>
          <div className="gold-rule mt-4" />
        </div>
        <div
          className="prose prose-sm max-w-none text-navy/80 leading-relaxed"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(proposal) }}
        />
        <div className="gold-rule mt-8" />
        <p className="text-center text-xs text-navy/40 mt-4 font-mono">
          Generated by ProposalForge • Powered by MiMo v2.5 Pro
        </p>
      </div>

      {/* Actions */}
      <div className="flex justify-between pt-2">
        <button
          onClick={onBack}
          className="px-6 py-3 text-slate border border-navy-mid rounded-lg hover:border-gold/50 transition-colors"
        >
          ← Edit Details
        </button>
        <button
          onClick={onReset}
          className="px-8 py-3 bg-gold text-navy font-semibold rounded-lg hover:bg-gold-dark transition-colors"
        >
          ✨ New Proposal
        </button>
      </div>
    </div>
  );
}
